import { FormEvent, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Spinner } from "../components/Spinner";
import { useLang } from "../i18n/LanguageContext";
import { isMockMode, supabase } from "../lib/supabaseClient";

const API_BASE = import.meta.env.VITE_API_BASE_URL as string;

export function NewIdea() {
  const { jihaCode = "casablanca" } = useParams();
  const navigate = useNavigate();
  const { tr } = useLang();

  const [name, setName] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [openToCollab, setOpenToCollab] = useState(true);
  const [contactInfo, setContactInfo] = useState("");
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [departmentId, setDepartmentId] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    // The PDF is required by the platform rules — refuse to submit without it.
    if (!pdfFile) {
      setError(tr.newIdea.pdfRequired);
      return;
    }
    if (pdfFile.type !== "application/pdf") {
      setError(tr.newIdea.pdfType);
      return;
    }

    setSubmitting(true);

    if (isMockMode || !supabase) {
      // Demo mode: no backend to store the idea — simulate success.
      await new Promise((r) => setTimeout(r, 500));
      setSubmitting(false);
      navigate("/board/submitted");
      return;
    }

    try {
      // 1. Upload the PDF to a private Supabase Storage bucket.
      //    Bucket "idea-pdfs" must be created as PRIVATE — access to the
      //    file is only ever granted through signed URLs generated by the
      //    backend for unlocked users.
      const { data: session } = await supabase.auth.getSession();
      const userId = session.session?.user.id;
      const path = `${jihaCode}/${userId}/${Date.now()}-${pdfFile.name}`;

      const { error: uploadError } = await supabase.storage.from("idea-pdfs").upload(path, pdfFile);
      if (uploadError) throw uploadError;

      // 2. Create the idea via the backend with the storage path.
      const res = await fetch(`${API_BASE}/api/jihat/${jihaCode}/ideas`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.session?.access_token}`,
        },
        body: JSON.stringify({
          name,
          title,
          description,
          departmentId,
          openToCollab,
          pdfUrl: path,
          contactInfo,
        }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? tr.newIdea.createFailed);
      }

      const idea = await res.json();
      navigate(`/jihat/${jihaCode}/ideas/${idea.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : tr.newIdea.unexpected);
    } finally {
      setSubmitting(false);
    }
  }

  const inputStyle: React.CSSProperties = {
    padding: "0.6em",
    borderRadius: "var(--radius-control)",
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
    color: "var(--color-text-primary)",
    fontFamily: "inherit",
  };

  return (
    <main className="page" style={{ maxWidth: 620 }}>
      <h2>{tr.newIdea.title}</h2>
      <p style={{ color: "var(--color-text-muted)", fontSize: "0.9rem" }}>{tr.newIdea.sub}</p>

      <form onSubmit={handleSubmit} style={{ display: "grid", gap: "0.9rem", marginTop: "1rem" }}>
        <input style={inputStyle} required placeholder={tr.newIdea.name} value={name} onChange={(e) => setName(e.target.value)} />
        <input style={inputStyle} required placeholder={tr.newIdea.publicTitle} value={title} onChange={(e) => setTitle(e.target.value)} />
        <textarea
          style={{ ...inputStyle, minHeight: 100 }}
          required
          placeholder={tr.newIdea.desc}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <input
          style={inputStyle}
          required
          placeholder={tr.newIdea.dept}
          value={departmentId}
          onChange={(e) => setDepartmentId(e.target.value)}
        />
        <input
          style={inputStyle}
          required
          placeholder={tr.newIdea.contact}
          value={contactInfo}
          onChange={(e) => setContactInfo(e.target.value)}
        />

        <label style={{ display: "grid", gap: "0.35rem", fontSize: "0.9rem" }}>
          {tr.newIdea.pdfLabel}
          <input type="file" accept="application/pdf" onChange={(e) => setPdfFile(e.target.files?.[0] ?? null)} />
        </label>

        <label style={{ display: "flex", gap: "0.5rem", alignItems: "center", fontSize: "0.9rem" }}>
          <input type="checkbox" checked={openToCollab} onChange={(e) => setOpenToCollab(e.target.checked)} />
          {tr.newIdea.collabLabel}
        </label>

        {error && <p style={{ color: "var(--color-istiqlal-rose)", margin: 0 }}>{error}</p>}

        <button className="primary" type="submit" disabled={submitting}>
          {submitting && <Spinner size={16} className="spinner-inline" />}
          {submitting ? tr.newIdea.submitting : tr.newIdea.submit}
        </button>
      </form>
    </main>
  );
}
